# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docktree < Formula
  desc "Run Docker Compose services across multiple git worktrees without port conflicts"
  homepage "https://github.com/Bnjoroge1/Docktree"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bnjoroge1/Docktree/releases/download/v1.1.0/docktree_1.1.0_darwin_amd64.tar.gz"
      sha256 "50fa72c2a2965e62bc0365fdc675630a207ebc593a6dea23cb8e39aa3c6fdc71"

      define_method(:install) do
        bin.install "docktree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bnjoroge1/Docktree/releases/download/v1.1.0/docktree_1.1.0_darwin_arm64.tar.gz"
      sha256 "8a10d8f6d8e7d34c1bb0964033dd65c65e5ead3cc8e4310a0191af960f594851"

      define_method(:install) do
        bin.install "docktree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bnjoroge1/Docktree/releases/download/v1.1.0/docktree_1.1.0_linux_amd64.tar.gz"
      sha256 "1898e6235c1caeb557736f63561a3c102ace7a994cd3cadf86fff21a869d78d9"
      define_method(:install) do
        bin.install "docktree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bnjoroge1/Docktree/releases/download/v1.1.0/docktree_1.1.0_linux_arm64.tar.gz"
      sha256 "d4332376cbfc1e683d01be410268864c46ac9bf2c7c10336067e9d92bc6832c7"
      define_method(:install) do
        bin.install "docktree"
      end
    end
  end
end
